security:

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                failure_path: login
                check_path: login
                #rewriting service to handle login success and failure
                success_handler: crv.authentication_success_handler
                failure_handler: crv.authentication_failure_handler

            logout:
                path: logout
                target: home
            remember_me:
                secret: '%kernel.secret%'
                name: 'REMEMBERME'
                lifetime: 604800 #1week in seconds
                path: /
                #uncomment the following line to always enable it
                #always_remember_me: true

    hide_user_not_found: false


    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
